### PR TITLE
Articlepage

### PR DESCRIPTION
**Pull request by FelipeEnne**
waiting for a code review

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team! image

#### Great job!  Wow, your README is very detailed. Love the effort you have put in.  Looks :+1: 

### Navigation bar needs little changes:
Great that you use  the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links and Navigation bar have a fixed position (it sticks to the top part of the screen). 
- [ ] But here should be a "Hamburger button" and link with text "space & cosmos" 
on the leftmost side.

- [ ] The NY Times logo should be a link.

### Main Content :+1: 

Very good that you use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

### Bottom part looks very good :+1:  but needs little changes:

Very good that you contains links to other articles with image previews on the leftmost side.
* [ ] But Also It should contains links to more popular articles on the rightmost side, under the text "Most popular".

### Footer
Great that you use the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer

### Make these changes and submit another code review request.

*If you have any questions, let me know here or on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by ricardovaltierra** [comment]
Fixed linking on the top navbar and "Most Popular" section of the page.

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Team,👋
Good job on implementing the changes suggested by my colleague earlier.🙂
Here is one fix we have to make to get this project approved.

* [ ] let us add the footer for this project.🙂
In this project, the footer is fixed to the bottom with an inscription ```"Access more of the times by creating a free an account or logging in"```. check the original [page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

### That is it, team, make these changes and subject project for reviews🙂

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
#### Happy coding😇

**Review by suretrust — APPROVED** [review]
Hi team,

Amazing job! :raised_hands: 
### Approved. :+1: Let's get this merged.

Good luck with your future projects and happy coding! :tada:

**Pull request merged**
